Repository jenkins-x/jenkins-x-image, pull requests merged in 2019-07, with the labels that each got.

#66 feat: adding static master bdd tests to project
  .gitignore
  jenkins-x.yml
  jx/bdd/static/README.md
  jx/bdd/static/ci.sh
  jx/bdd/static/cluster.yaml
  myvalues.yaml.static.template
Labels: approved, lgtm, size/M

#67 chore(deps): bump jenkins from 2.164.3 to 2.176.1
  Dockerfile
  jenkins-x.yml
Labels: approved, size/XS

#68 chore: enabled changelog in release pipeline
  docs/dev/changelog-footer.md
  docs/dev/changelog-header.md
  jenkins-x.yml
  jx/scripts/changelog.sh
Labels: approved, size/XS

#69 fix: changing image for updatebot & changelog
  jenkins-x.yml
Labels: approved, size/XS

#70 fix: using maven based image to run updatebot
  jenkins-x.yml
Labels: approved, size/XS

#71 fix: reorder to test out changelog
  jenkins-x.yml
Labels: approved, size/XS

#72 chore: switch to new updatebot
  updatebot.sh
Labels: approved, size/XS

#73 fix: using exact versions for updatebot & changelog
  jenkins-x.yml
  jx/scripts/changelog.sh
Labels: approved, size/XS

#74 chore: correct path in jenkins-x-platform repo
  updatebot.sh
Labels: approved, size/XS

#75 fix: Security fix upgrading to 2.176.2
  Dockerfile
Labels: approved, lgtm, size/XS
