Repository jenkins-x/jenkins-x-image, pull requests merged in 2019-04, with the labels that each got.

#57 chore: update base image to 2.150.3-slim
  Dockerfile
Labels: approved, size/XS

#44 Add gitignore for idea
  .gitignore
Labels: approved, ok-to-test, size/XS

#45 Add localization-zh-cn plugin
  plugins.latest
  plugins.txt
Labels: approved, ok-to-test, size/XS

#58 feat: adding tekton pipeline
  Jenkinsfile
  jenkins-x.yml
  updatebot.sh
Labels: approved, size/L

#60 feat: removed unused script
  jx/scripts/release.sh
Labels: approved, size/S

#61 chore: updating to Jenkins LTS 2.164.2
  Dockerfile
  jenkins-x.yml
Labels: approved, size/S
